import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Carbon Calculator</a>
        </h1>
        <p>Car-brand</p><input></input>
        <p>Model</p><input></input>
        <p>Year</p><input></input>
        <p>Distance</p><input></input>
      
        <button>Calculate</button>
      </main>

      <footer className={styles.footer}>
        <h1>Dancer</h1>
      </footer>
    </div>
  )
}
